meta_product_name: "Wolfgang"
meta_title: "Wolfgang - play music scores, annotate and share anywhere"
meta_description: "Wolfgang is for classical music players. Find a score or add your own. Annotate and share it. Play effortlessly anywhere with our page turning feature"
meta_image: "wolfgang_cover_image.png"
twitter_account: "@gaelgendre"
